services:
  db:
    container_name: elearning_db
    image: postgres:17
    ports:
      - '5432:5432'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: elearning
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345

volumes:
  pgdata: null
