name: 02-postgres-mercadolibre

services:
  database: 
    container_name: mercadolibre
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

    environment:
      POSTGRES_DB: mercadolibre
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345

volumes:
  pgdata: null